project_id = "bliwnrikjfzcialoznur"

[functions.generate-report]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = true

[functions.nvd-proxy]
verify_jwt = true

[functions.run-scheduled-scans]
verify_jwt = false